export const TEAM = [
  { name: "Maya", title: "Market Scout", bio: "I have my eyes on every street in the GTA. I spot the deals before they hit the public market.", insight: "Market Tip: Inventory in the Beaches is tightening - act fast.", roleHighlight: "Expertly analyzes market data to uncover off-market opportunities.", aboutMe: "A lifelong Torontonian with a passion for urban development, Maya leverages high-tech data scraping tools to pinpoint emerging neighborhoods long before they reach mainstream investor attention.", socialLinks: { linkedin: "#", twitter: "#", instagram: "#" }, image: "https://picsum.photos/seed/maya/200/200" },
  { name: "Elias", title: "Outreach Lead", bio: "I’m the bridge builder. I connect Paul’s buyers with sellers who haven't even listed yet.", insight: "Weekly Update: 4 new off-market opportunities in Rosedale.", roleHighlight: "Builds strategic relationships to bridge buyers and sellers.", aboutMe: "Elias brings a decade of high-stakes negotiations experience, specializing in off-market transactions. He is the master of empathy, turning cold leads into warm partnerships.", socialLinks: { linkedin: "#", twitter: "#", instagram: "#" }, image: "https://picsum.photos/seed/elias/200/200" },
  { name: "Sarah", title: "Concierge", bio: "I’m the gatekeeper. I protect Paul’s time by ensuring every meeting on his calendar is a high-value opportunity.", insight: "Pro-Tip: Prepare your financial pre-approval before our initial consult.", roleHighlight: "Optimizes Paul’s calendar for maximum impact and value.", aboutMe: "With a background in luxury hospitality, Sarah ensures every client interaction is flawlessly prepped and personalized, managing the complexities of schedule so that focus remains on the client.", socialLinks: { linkedin: "#", twitter: "#", instagram: "#" }, image: "https://picsum.photos/seed/sarah/200/200" },
  { name: "Vince", title: "Partner Manager", bio: "I know the best trades in Toronto. If you need a kitchen done right, I’ve got the contractor on speed-dial.", insight: "Trade Alert: Lead times for custom cabinets are currently 6-8 weeks.", roleHighlight: "Curates and manages a premier network of trusted trade partners.", aboutMe: "Vince is a former construction project manager who turned to real estate. He vets every single trade professional, ensuring that any renovation or repair meets the elite standards of McKennon clients.", socialLinks: { linkedin: "#", twitter: "#", instagram: "#" }, image: "https://picsum.photos/seed/vince/200/200" },
  { name: "Bella", title: "Vision Specialist", bio: "I see the potential in every room. I turn 'fixer-uppers' into dream homes before you even sign the papers.", insight: "Design Idea: A coat of 'Swiss Coffee' white completely transforms this era's condos.", roleHighlight: "Visualizes architectural potential to elevate property value.", aboutMe: "Armed with an Interior Design degree and a keen eye for resale value, Bella helps clients see past dated finishes. She turns potential into equity through targeted aesthetics.", socialLinks: { linkedin: "#", twitter: "#", instagram: "#" }, image: "https://picsum.photos/seed/bella/200/200" },
  { name: "Penny", title: "Moving Assistant", bio: "I handle the logistics. From hydro to high-speed internet, I make sure your move-in day is stress-free.", insight: "Logistics Checklist: Book your elevator move service at least 14 days out.", roleHighlight: "Orchestrates seamless logistics for stress-free transitions.", aboutMe: "Penny is the master of organizational chaos. She specializes in the nitty-gritty of moving, ensuring that the transition into a new home is as seamless as the transaction itself.", socialLinks: { linkedin: "#", twitter: "#", instagram: "#" }, image: "https://picsum.photos/seed/penny/200/200" },
];

export const LIVE_ACTIVITIES = [
  { agent: "Maya", text: "Spotted a new condo listing in Markham.", type: "market" },
  { agent: "Bella", text: "Staged a stunning Yorkville condo.", type: "design" },
  { agent: "Elias", text: "Secured off-market access in Forest Hill.", type: "outreach" },
  { agent: "Vince", text: "Vetted a top-tier contractor for North York.", type: "trades" },
  { agent: "Sarah", text: "Confirmed 3 high-value meetings for Paul.", type: "concierge" },
  { agent: "Penny", text: "Orchestrating a seamless move-in in Etobicoke.", type: "moving" },
  { agent: "Maya", text: "Identified a price drop in The Beaches.", type: "market" },
  { agent: "Maya", text: "Flagged a luxury townhouse in Oakville.", type: "market" },
  { agent: "Bella", text: "Selected color palette for a Rosedale reno.", type: "design" },
  { agent: "Elias", text: "Connecting buyer to luxury seller in Bridal Path.", type: "outreach" },
  { agent: "Vince", text: "Approved painter for a bungalow in Vaughan.", type: "trades" },
  { agent: "Sarah", text: "Scheduled deep-dive financial consult for client.", type: "concierge" },
  { agent: "Penny", text: "Coordinating utility handovers for condo conversion.", type: "moving" },
];
